// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_M417rygW1d1T_gEhPJAILSXskM3ZeaA',
    appId: '1:32125673340:android:34fdaa0eb623f1a926cef9',
    messagingSenderId: '32125673340',
    projectId: 'uniconnect-f2328',
    storageBucket: 'uniconnect-f2328.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCd2ES9kBB8kk_vvnC-I9niNWswVhbwPnY',
    appId: '1:32125673340:web:5766628ac6ef238326cef9',
    messagingSenderId: '32125673340',
    projectId: 'uniconnect-f2328',
    authDomain: 'uniconnect-f2328.firebaseapp.com',
    storageBucket: 'uniconnect-f2328.firebasestorage.app',
    measurementId: 'G-BKJNNWKTKD',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCd2ES9kBB8kk_vvnC-I9niNWswVhbwPnY',
    appId: '1:32125673340:web:346af980a1ff63da26cef9',
    messagingSenderId: '32125673340',
    projectId: 'uniconnect-f2328',
    authDomain: 'uniconnect-f2328.firebaseapp.com',
    storageBucket: 'uniconnect-f2328.firebasestorage.app',
    measurementId: 'G-XSX3S0HRTC',
  );

}